[build-system]
requires = ["setuptools >= 65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gribmanager"
version = "0.2"
dependencies = [
  "numpy >= 1.23.5",
  "pandas >= 1.5.2",
  "xarray >= 2023.6.0",
  "eccodes == 2.18.0",
]
requires-python = ">= 3.9"
readme = "README.md"
